### ISSUE TITLE
[Bug] Fly disabling when changing worlds

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#109]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

uekc

### Server Version

1.21.1

### Server Software

[15:43:50 INFO]: Current Purpur Version: 1.21.1-2321-2eaea6a (MC: 1.21.1)*

### zEssentials Version

[15:44:01 INFO]: zEssentials version 1.0.1.1

### zMenu Version

[15:44:18 INFO]: zMenu version 1.0.3.5

### What happened?

When a player goes from world 1 to world 2, their fly gets disabled. This is especially dangerous if a player teleports to a player in another world while flying.

### Steps to reproduce the issue

1. Enable flight with /fly
2. Go to another world
3. Try to fly
4. See that fly is disabled

### Full Server Log

https://mclo.gs/yDrrnHB

**Comment by Maxlego08** [comment]
Fixed with 1.0.1.2
