### ISSUE TITLE
[Suggestion] Tab completion for editing hologram and itemrename

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#116]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I already searched on this [Github page](https://github.com/Maxlego08/zEssentials/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this or if the feature was already suggested.

### Discord Username (optional)

uekc

### Describe your suggestions

When editing a hologram, it would be nice to have tab completion.
For instance with `/holo setline`. Then you don't have to retype the whole line if you only want to edit a little part of it. Also very handy if your hologram consists of complex placeholders, otherwise you have tor retype everything.
Please also add this for `/itemrename` and `/lore`

**Comment by Maxlego08** [comment]
Done !
