### ISSUE TITLE
[Bug] Chat color plugins not working

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#118]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

uekc

### Server Version

1.21.1

### Server Software

[13:50:21 INFO]: Current Purpur Version: 1.21.1-2321-2eaea6a (MC: 1.21.1)*

### zEssentials Version

[13:49:59 INFO]: zEssentials version 1.0.1.2

### zMenu Version

[13:50:07 INFO]: zMenu version 1.0.3.5

### What happened?

Chatcolors stopped working when I switched to zEssentials Chat module.
I use this chatcolor plugin: https://www.spigotmc.org/resources/chatcolor-%E2%9C%A8-custom-patterns-%E2%9C%85-full-configurable.93186/

### Steps to reproduce the issue

1. Use zEssentials chat module
2. Use [chatcolor](https://www.spigotmc.org/resources/chatcolor-%E2%9C%A8-custom-patterns-%E2%9C%85-full-configurable.93186/) plugin
3. Enable a chat color
4. Send message in chat
5. See that the chatcolors don't work

### Full Server Log

https://mclo.gs/zGBCdxy

**Comment by Maxlego08** [comment]
Unfortunately this kind of plugin may not be compatible with zEssentials.

**Comment by MrLouisDew** [comment]
Then what chatcolor plugin is?
