### ISSUE TITLE
[Bug] Removed homes showing up again

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#119]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

uekc

### Server Version

1.21.1

### Server Software

[14:37:13 INFO]: Current Purpur Version: 1.21.1-2321-2eaea6a (MC: 1.21.1)*

### zEssentials Version

[14:37:22 INFO]: zEssentials version 1.0.1.2

### zMenu Version

[14:37:32 INFO]: zMenu version 1.0.3.5

### What happened?

When players remove a home, they show up again later.
home-usage-type is STACK. 

### Steps to reproduce the issue

1. Make a home
2. Delete home
3. Wait
4. Look at your homes
5. See that the removed home is back

### Full Server Log

https://mclo.gs/enrXYeT

**Comment by Maxlego08** [comment]
Fixed !
