### ISSUE TITLE
[request] basic userdata script for migrating from essentials to zessentials (sql)

### ISSUE THREAD

**Issue by modpotato** [Maxlego08/zEssentials#17]
mainly because i dont know the schema of the sql db i dont want to make it myself, a simple python script or even a built in migrator would be awesome though

**Comment by Maxlego08** [comment]
> made a basic one in python just for my sake though id still love to see this https://gist.github.com/modpotato/00302926c81dfff5e1b4e3b12099d0c5

OMG, I will tell users that there is this solution, and as much as possible I would make a command in the plugin to convert the data
