### ISSUE TITLE
[FEATURE] Hologram background transparent

### ISSUE THREAD

**Issue by DxrkCat** [Maxlego08/zEssentials#26]
Add the ability to make the background of the hologram transparent.
![изображение](https://github.com/user-attachments/assets/2976594f-d0de-496b-b5b4-b3b27a3c8b76) (like CMI)
![изображение](https://github.com/user-attachments/assets/336e1b63-09b6-46dd-b9c8-ed1b7809bbbb)

**Comment by Maxlego08** [comment]
You can already do it: https://github.com/Maxlego08/zEssentials/blob/master/src/main/java/fr/maxlego08/essentials/commands/commands/hologram/text/CommandHologramBackground.java
