### ISSUE TITLE
Feed permission not working

### ISSUE THREAD

**Issue by Scrawble** [Maxlego08/zEssentials#60]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

Scrawble

### Server Version

1.20.4

### Server Software

AxolotlSpigot 1.20.1 1.2.8

### zEssentials Version

1.0.0.6

### zMenu Version

1.0.3.3

### What happened?

when you do /feed (with the perm essentials.feed *(non opped)* it doesnt work it just shows the usage of /feed <player>

### Steps to reproduce the issue

give a non opped player essentials.feed
run /feed

### Full Server Log

dont need/have

**Comment by Maxlego08** [comment]
![image](https://github.com/user-attachments/assets/47db3cd7-2d02-4178-937e-297efdc4b286)
I just tried with a double account, and I have no problem, the only reason can return this is that the player is not found, did you have more informations ?

**Comment by Scrawble** [comment]
![image](https://github.com/user-attachments/assets/af51f330-9273-45e5-a89f-c18c64e7aadd)
It keeps doing this. Even if i type a player it doesnt work and sends the same message

**Comment by Maxlego08** [comment]
Enable debug mode and send me server logs plz !
