### ISSUE TITLE
Issue with "world" when it is removed from server

### ISSUE THREAD

**Issue by Scrawble** [Maxlego08/zEssentials#67]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

Scrawble

### Server Version

1.20.4

### Server Software

Version AxolotlSpigot 1.20.1

### zEssentials Version

Essentials 1.0.0.6

### zMenu Version

Version 1.0.3.3

### What happened?

When a player logs in it has an error that says something about the "world" folder not existing. I removed it and renamed it to Survival for my own aesthetic pleasing

### Steps to reproduce the issue

Remove the "world" file from ur server permanently

### Full Server Log

https://mclo.gs/sKfDDjw

**Comment by Maxlego08** [comment]
Hey, you cant rename a world like that.

2 options: 
- Reset the world name to "world"
- Update the database content and replace every "world" by "Survival"
