### ISSUE TITLE
MySQL Problem

### ISSUE THREAD

**Issue by Tibarica** [Maxlego08/zEssentials#69]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

tiba3625

### Server Version

1.21.1

### Server Software

This server is running Folia version 1.21.1-DEV-dev/1.21.1@bfa3106 (2024-08-25T01:34:26Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-9203a7a (MC: 1.21.1)

### zEssentials Version

1.0.0.7

### zMenu Version

1.0.3.4

### What happened?

I’m running into a problem with the zEssentials plugin on my Minecraft server when attempting to use MySQL as the storage option. The server successfully connects to the MySQL database, but during initialization, several tables fail to be created due to foreign key constraints that are incorrectly formed.

### Steps to reproduce the issue

-Set up a Minecraft server using Folia 1.21.1.
-Install the zEssentials 1.0.0.7, zMenu 1.0.3.4, PlaceholderAPI 2.11.7-DEV-null, Vault 1.7.3 plugin on the server.
-Configure the plugin to use MySQL as the storage option with your database settings
-Start the server and observe the logs during the initialization phase.
-Note the SQL errors related to the creation of tables with foreign key constraints that are incorrectly formed.

Expected behavior: The plugin should create the necessary tables in the MySQL database without errors.

Actual behavior: The plugin fails to create several tables due to foreign key constraint errors, leading to subsequent SQL errors when trying to interact with the database.

### Full Server Log

https://mclo.gs/FAKya4c

**Comment by Maxlego08** [comment]
Can you send me your config.yml file and database content

**Comment by Tibarica** [comment]
[Config & Database.zip](https://github.com/user-attachments/files/16840799/Config.Database.zip)

**Comment by Maxlego08** [comment]
![image](https://github.com/user-attachments/assets/31830949-42a5-4fbe-9c6f-9b72b0062201)
never change that, let zessentials_

**Comment by Tibarica** [comment]
Did that with a new and updated zEssentials/config. and still have errors
https://mclo.gs/3OPbQxt
[Config Updated.zip](https://github.com/user-attachments/files/16852748/Config.Updated.zip)
