### ISSUE TITLE
/day and /night command does not work

### ISSUE THREAD

**Issue by JavaToastDev** [Maxlego08/zEssentials#71]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

javaToast

### Server Version

1.21.1

### Server Software

This server is running Folia version 1.21.1-DEV-dev/1.21.1@88e0907 (2024-09-01T16:32:08Z)
(Implementing API version 1.21.1-R0.1-SNAPSHOT)

### zEssentials Version

zEssentials version 1.0.0.7

### zMenu Version

zMenu version 1.0.3.4

### What happened?

The /day and /night command doesn't work, nothing happens even if I do /day world or /night world. It just gives me the wrong usage message.

### Steps to reproduce the issue

1. Join the game
2. Execute /day or /night

### Full Server Log

https://mclo.gs/dM69dEZ

### Screenshots/Videos (you can drag and drop files or paste links)

![Desktop Screenshot 2024 09 02 - 12 43 52 91](https://github.com/user-attachments/assets/0ca10492-cd1a-4d3d-8115-d94db57fa680)

**Comment by Maxlego08** [comment]
You have an error with your database, plz show me your config.yml file

**Comment by JavaToastDev** [comment]
> You have an error with your database, plz show me your config.yml file

Im using the DEFAULT config.
Storage method: SQLite

**Comment by Maxlego08** [comment]
> > You have an error with your database, plz show me your config.yml file
> 
> Im using the DEFAULT config. Storage method: SQLite

send me your database.db file plz

**Comment by JavaToastDev** [comment]
I reset the database file several times, hoping it would work.
GitHub won't allow me to send the database file here, should I open a ticket?

**Comment by Maxlego08** [comment]
Yeah plz open a ticket on my discord, or you can try to send a zip file ?

**Comment by JavaToastDev** [comment]
[files.zip](https://github.com/user-attachments/files/16836927/files.zip)

**Comment by Maxlego08** [comment]
Okay, I confirm that we have the same problem!
