### ISSUE TITLE
[BUG] Holograms are duplicated in locations between worlds

### ISSUE THREAD

**Issue by DxrkCat** [Maxlego08/zEssentials#80]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server.
- [X] I enabled the debug mode in config.yml and sql debug

### Server Version

1.21.1

### Server Software

Purpur 1.21.1-2301

### zEssentials Version

1.0.0.8 master

### zMenu Version

1.0.3.4

### What happened?

I create a hologram in the world 'test' at coordinates 0.5, 111, 0.5 and if I teleport to the world 'world' at coordinates 0.5, 111, 0.5. These holograms will be there too.

### Steps to reproduce the issue

1) hologram create TEXT test
2) Moving between worlds via MultiverseCore

### Full Server Log

none

### Error (optional)

```shell
no errors
```

**Comment by breitwan** [comment]
Same

**Comment by DxrkCat** [comment]
[Mention] I gave up on your holograms by migrating back to FancyHolograms. So I won't be able to check if this bug has been fixed

**Comment by Maxlego08** [comment]
Done
