### ISSUE TITLE
Stack Home Permissions

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zEssentials#84]
### Terms

- [X] I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI).
- [X] I already searched on this [Github page](https://github.com/Maxlego08/zEssentials/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this or if the feature was already suggested.

### Discord Username (optional)

uekc

### Describe your suggestions

When a player has multiple home permissions. The amount of homes stack. Right now it is only possible to use the maximum number of homes. Please add this, this is essential.

**Comment by Maxlego08** [comment]
I did not understand what you want to do, can you explain better?

**Comment by MrLouisDew** [comment]
The config states the following.
`# If the player has multiple permissions then the maximum number of home will be used.`
Now, I would love to see an option to change this. I want if a player has multiple home permissions the amount will stack.
For example:

Player Louis_Dew has the following permissions:

- essentials.home.5 (representing 5 homes)
- essentials.home.10 (representing 10 homes)

Then the amount will stack, in this case the player would than have a total of 15 homes.
